// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kucnwjwwklohafazalfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Y253and3a2xvaGFmYXphbGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNTIzMjMsImV4cCI6MjA3ODYyODMyM30.u6c-vcDqqem6d5rxH2LeR2A5984Hr9V3fti4qzj0Pkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});