create table if not exists public.call_logs (
  id bigint generated by default as identity primary key,
  initiator_id bigint references public.users(id) not null,
  receiver_id bigint references public.users(id), -- null for group calls if we support them later, but mandatory for DM
  room_key text not null,
  started_at timestamptz default now(),
  ended_at timestamptz,
  status text check (status in ('missed', 'completed', 'rejected', 'ongoing')) default 'ongoing',
  created_at timestamptz default now()
);

alter table public.call_logs enable row level security;

create policy "Users can view their own calls"
  on public.call_logs for select
  using (
    exists (
      select 1 from public.users u
      where u.auth_user_id = auth.uid()
      and (u.id = initiator_id or u.id = receiver_id)
    )
  );

create policy "Users can insert call logs"
  on public.call_logs for insert
  with check (
    exists (
      select 1 from public.users u
      where u.auth_user_id = auth.uid()
      and u.id = initiator_id
    )
  );

create policy "Users can update their own calls"
  on public.call_logs for update
  using (
    exists (
      select 1 from public.users u
      where u.auth_user_id = auth.uid()
      and (u.id = initiator_id or u.id = receiver_id)
    )
  );
